import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  map: { flex: 1 },
  mapControls: {
    position: "absolute",
    top: 60,
    right: 16,
    alignItems: "center",
  },
  controlButton: {
    width: 48,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 24,
    marginVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  infoPanel: {
    position: "absolute",
    bottom: 24,
    left: 16,
    right: 16,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    padding: 16,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: "rgba(15, 160, 228, 0.05)",
  },
  roadName: {
    fontWeight: "700",
    fontSize: 18,
    color: "#333",
    marginBottom: 12,
  },
  checkButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1e90ff",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    minHeight: 48,
  },
  checkButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  participantCount: { fontSize: 12, color: "#666", marginTop: 2 },
  disabledButton: { backgroundColor: "#ccc" },
  roomInfoContainer: {
    backgroundColor: "rgba(240, 240, 240, 0.9)",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  usernameTitle: { fontSize: 20, fontWeight: "700", color: "#333" },
  usernameContent: {
    flex: 1,
    padding: 24,
    justifyContent: "center",
    marginTop: -50,
  },
  usernameSubtitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#333",
    marginBottom: 32,
    textAlign: "center",
  },
  usernameForm: { marginBottom: 32 },
  inputLabel: {
    fontSize: 16,
    color: "#333",
    marginBottom: 8,
    fontWeight: "500",
  },
  jamMarker: {
    backgroundColor: "rgba(255,255,255,0.9)",
    padding: 10,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#ff4757",
    shadowColor: "#ff4757",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 5,
  },
  simulateButton: {
    backgroundColor: "rgba(46, 213, 115, 0.2)",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 12,
    borderWidth: 1,
    borderColor: "rgba(46, 213, 115, 0.3)",
  },
  simulateButtonText: {
    color: "#2ed573",
    fontSize: 16,
    fontWeight: "600",
  },
  roomInfoTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginBottom: 10,
    textAlign: "center",
  },
  roomItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  roomName: { fontSize: 16, color: "#333" },
  roomParticipants: { fontSize: 14, color: "#666" },
  usernameContainer: { flex: 1, backgroundColor: "#fff" },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.8)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  loadingText: { marginTop: 12, fontSize: 16, color: "#333" },
  usernameHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    paddingTop: 60,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  continueButton: {
    backgroundColor: "#1e90ff",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 20,
  },
  continueButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginRight: 10,
  },
  usernameInput: {
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 12,
    padding: 16,
    color: "#333",
    fontSize: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  iconGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 8,
  },
  iconButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "rgba(19, 17, 17, 0.9)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "transparent",
  },
  selectedIconButton: {
    borderColor: "#1e90ff",
    backgroundColor: "rgba(240, 240, 240, 1)",
    transform: [{ scale: 1.1 }],
  },
  messagesContainer: { flex: 1, backgroundColor: "#fff" },
  messagesContent: { paddingBottom: 20, paddingTop: 10 },
  otherUserText: { color: "#333" },
  messageContainer: {
    padding: 12,
    marginHorizontal: 16,
    marginVertical: 8,
    borderRadius: 16,
    maxWidth: "80%",
  },
  messageText: { fontSize: 16, lineHeight: 22 },
  currentUserMessage: {
    alignSelf: "flex-end",
    backgroundColor: "#2e2d2d",
    borderTopRightRadius: 4,
  },
  otherUserMessage: {
    alignSelf: "flex-start",
    backgroundColor: "#f0f0f0",
    borderTopLeftRadius: 4,
  },
  messageHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  messageUsername: {
    fontWeight: "600",
    marginLeft: 6,
    marginRight: 10,
    fontSize: 14,
  },
  typingContainer: {
    padding: 10,
    paddingBottom: 20,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  currentUserText: { color: "#fff" },
  chatContainer: { flex: 1, backgroundColor: "#fff" },
  connectionStatus: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(240,240,240,0.9)",
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  chatTitle: { fontSize: 20, fontWeight: "700", color: "#333" },
  chatSubtitle: { fontSize: 14, color: "#1e90ff", marginTop: 4 },
  backButton: {
    backgroundColor: "rgba(240, 240, 240, 0.9)",
    borderRadius: 20,
    padding: 8,
  },
  connectionDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#ff4757",
    marginRight: 5,
  },
  connectedDot: { backgroundColor: "#2ed573" },
  messageTime: { color: "#888", fontSize: 12 },
  systemMessageContainer: {
    alignItems: "center",
    marginVertical: 10,
  },
  systemMessageText: {
    color: "#888",
    backgroundColor: "rgba(240, 240, 240, 0.9)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    fontSize: 14,
  },
  connectionText: { color: "#333", fontSize: 12 },
  chatHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    paddingTop: 60,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  typingText: { color: "#666", fontStyle: "italic", marginLeft: 8 },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  textInput: {
    flex: 1,
    backgroundColor: "rgba(240, 240, 240, 0.9)",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    color: "#333",
    fontSize: 16,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  sendButton: {
    backgroundColor: "#1e90ff",
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  chatHeaderCenter: {
    alignItems: "center",
    flex: 1,
  },
  dataRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  dataItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  dataText: {
    marginLeft: 6,
    fontSize: 16,
    fontWeight: "500",
    color: "#555",
  },
  jamAlert: {
    backgroundColor: "rgba(255, 71, 87, 0.1)",
    borderRadius: 16,
    padding: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#ff4757",
  },
  jamHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  jamTitle: { fontWeight: "700", fontSize: 18, color: "#ff4757" },
  endSimulationText: { color: "#1e90ff", fontWeight: "500", fontSize: 14 },
  jamDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  jamDetailItem: { alignItems: "center" },
  jamDetailLabel: { fontSize: 14, color: "#777", marginBottom: 4 },
  jamDetailValue: { fontSize: 18, fontWeight: "700", color: "#333" },
  highSeverity: { color: "#ff4757" },
  findingPeople: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  findingPeopleText: {
    marginLeft: 8,
    color: "#1e90ff",
    fontWeight: "500",
  },
  roomFoundText: {
    marginTop: 8,
    color: "#2ed573",
    fontWeight: "600",
    textAlign: "center",
  },
  noJamContainer: { alignItems: "center", paddingVertical: 8 },
  noJam: { fontSize: 16, fontWeight: "500", color: "#2ed573" },
  joinButton: {
    backgroundColor: "#1e90ff",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
    flexDirection: "row",
    justifyContent: "center",
  },
  joinIcon: { marginLeft: 8 },
  joinButtonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
});